# ML-02 — Research Question and Provisional Lane

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Arexreva/flyrank-internship-ML/blob/main/work/notebooks/w01_research_question.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane (or freestyle) and why

*WebPage refresher*

I selected **Lane 2 – Refresh / Content Opportunity Scoring**.

The goal of this project is to help prioritize which content pages should be reviewed first for refresh or improvement. Large websites often contain hundreds of thousands of pages, making manual review difficult and time-consuming.

Instead of reviewing pages randomly, this project aims to rank pages using historical search performance and engagement signals. This allows SEO and content teams to focus their effort on pages that are more likely to benefit from review.

I chose this lane because it addresses a real business problem by improving decision-making rather than simply building a machine learning model.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. The question: decision, action, cost of a wrong call

## Research Question

Which content pages should be prioritized for review based on historical search performance and engagement signals?

## Decision

The decision is to identify which pages should be reviewed first by the SEO or content team.

## Action

After reviewing the recommendations, the team may refresh the content, improve metadata, update information, expand the page, monitor its performance, or decide that no action is currently needed.

## Cost of a Wrong Recommendation

If a healthy page is incorrectly recommended, valuable review time is wasted.

If a declining page is not identified, it may continue losing search visibility and traffic, reducing the opportunity to improve its performance.

## Why Machine Learning?

The content inventory is too large for manual review. Machine learning can learn patterns from historical search and engagement signals and rank pages according to their likelihood of requiring review, helping the team prioritize its limited resources.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 3. Quick look at the data (2-3 real numbers)

The starter dataset contains **30,000** content pages collected from **32** different clients. Each content page is represented using **44 features**, which include both content metadata and historical SEO performance metrics.

The available features include search volume, impressions, clicks, sessions, CTR, average search position, content age, freshness, engagement metrics, and trend information. From the exploratory analysis, the average search volume is **158.88**, the average CTR is **0.51**, and the average search position is **16.34**.

These statistics indicate that the dataset contains sufficient information to study content performance and identify pages that may require refreshing. Since reviewing thousands of pages manually is impractical, machine learning can help rank and prioritize pages that are most likely to benefit from updates, supporting the objective of **Lane 2 – Refresh / Content Opportunity Scoring**.

In [19]:
# Basic dataset statistics
print("Number of Rows:", len(df))
print("Number of Columns:", len(df.columns))
print("Unique Clients:", df["client_id"].nunique())
print("Unique Content Pages:", df["content_id"].nunique())

print("\nAverage Search Volume:", round(df["search_volume"].mean(), 2))
print("Average CTR:", round(df["ctr"].mean(), 2))
print("Average Position:", round(df["avg_position"].mean(), 2))

Number of Rows: 30000
Number of Columns: 44
Unique Clients: 32
Unique Content Pages: 30000

Average Search Volume: 158.88
Average CTR: 0.51
Average Position: 16.34

In [22]:
# Check for duplicate content pages
print("Duplicate Content IDs:", df["content_id"].duplicated().sum())

# Check missing values
missing = df.isnull().sum()
print("\nColumns with Missing Values:")
print(missing[missing > 0])

Duplicate Content IDs: 0

Columns with Missing Values:
search_volume         2468
competition           2468
competition_level     2610
cpc                   2468
main_intent           2374
word_count            7699
char_count            7699
provider_used        21438
model_used            5733
word_count_tier       7699
char_count_tier       7699
scroll_rate            125
trend_pct             3388
dtype: int64

In [20]:
# Display the first five rows
df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,provider_used,model_used,impressions_90d,clicks_90d,pageviews_90d,sessions_90d,users_90d,engaged_sessions_90d,ai_sessions_90d,scroll_events_90d,days_with_impressions,days_with_sessions,impressions_last_30d,clicks_last_30d,sessions_last_30d,impressions_prev_30d,clicks_prev_30d,sessions_prev_30d,content_age_days,age_tier,age_tier_order,days_since_last_update,freshness_tier,word_count_tier,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,NaN,gemini-2.5-flash,3803,29,22,17,16,1,0,1,88,13,578,2,2,987,13,9,187,181-365,5,20,0-30,2000-3500,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,NaN,gemini-3-flash-preview,15320,7,10,9,9,0,0,1,88,9,2501,2,3,5915,1,2,445,365+,6,25,0-30,2000-3500,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,NaN,gemini-2.5-flash,12581,11,14,11,11,0,0,4,88,11,2382,1,1,6089,3,3,141,91-180,4,20,0-30,3500+,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,NaN,NaN,11751,58,87,78,75,1,0,3,88,51,3626,22,35,4206,17,26,463,365+,6,22,0-30,NaN,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,NaN,gemini-3-flash-preview,19140,24,177,145,144,0,0,43,88,33,4211,10,14,6452,2,9,263,181-365,5,14,0-30,2000-3500,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [21]:
# Check for missing values
df.isnull().sum().sort_values(ascending=False).head(10)

provider_used        21438
word_count            7699
char_count            7699
word_count_tier       7699
char_count_tier       7699
model_used            5733
trend_pct             3388
competition_level     2610
search_volume         2468
cpc                   2468
dtype: int64

In [3]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [6]:
!git clone https://github.com/Arexreva/flyrank-internship-ML.git
%cd flyrank-internship-ML
!ls

Cloning into 'flyrank-internship-ML'...
remote: Enumerating objects: 131, done.
remote: Counting objects: 100% (131/131), done.
remote: Compressing objects: 100% (88/88), done.
remote: Total 131 (delta 44), reused 93 (delta 27), pack-reused 0 (from 0)
Receiving objects: 100% (131/131), 1.85 MiB | 15.05 MiB/s, done.
Resolving deltas: 100% (44/44), done.
/content/flyrank-internship-ML
AGENTS.md  DATA_USE.md	LICENSE    README.md	     SETUP.md	 work
CLAUDE.md  docs		notebooks  requirements.txt  skills
data	   GUIDE.md	outputs    scripts	     submission

In [7]:
!find . -name "*.csv"

./outputs/refresh_queue_sample.csv
./data/raw/content_refresh_anonymized.csv

In [8]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")
df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,provider_used,model_used,impressions_90d,clicks_90d,pageviews_90d,sessions_90d,users_90d,engaged_sessions_90d,ai_sessions_90d,scroll_events_90d,days_with_impressions,days_with_sessions,impressions_last_30d,clicks_last_30d,sessions_last_30d,impressions_prev_30d,clicks_prev_30d,sessions_prev_30d,content_age_days,age_tier,age_tier_order,days_since_last_update,freshness_tier,word_count_tier,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,NaN,gemini-2.5-flash,3803,29,22,17,16,1,0,1,88,13,578,2,2,987,13,9,187,181-365,5,20,0-30,2000-3500,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,NaN,gemini-3-flash-preview,15320,7,10,9,9,0,0,1,88,9,2501,2,3,5915,1,2,445,365+,6,25,0-30,2000-3500,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,NaN,gemini-2.5-flash,12581,11,14,11,11,0,0,4,88,11,2382,1,1,6089,3,3,141,91-180,4,20,0-30,3500+,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,NaN,NaN,11751,58,87,78,75,1,0,3,88,51,3626,22,35,4206,17,26,463,365+,6,22,0-30,NaN,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,NaN,gemini-3-flash-preview,19140,24,177,145,144,0,0,43,88,33,4211,10,14,6452,2,9,263,181-365,5,14,0-30,2000-3500,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              30000 non-null  object
 1   client_id               30000 non-null  object
 2   search_volume           27532 non-null  float64
 3   competition             27532 non-null  float64
 4   competition_level       27390 non-null  object
 5   cpc                     27532 non-null  float64
 6   content_type            30000 non-null  object
 7   main_intent             27626 non-null  object
 8   word_count              22301 non-null  float64
 9   char_count              22301 non-null  float64
 10  provider_used           8562 non-null   object
 11  model_used              24267 non-null  object
 12  impressions_90d         30000 non-null  int64
 13  clicks_90d              30000 non-null  int64
 14  pageviews_90d           30000 non-null  int64
 15  sessions_90d            30000 non-null  int64
 16  users_90d               30000 non-null  int64
 17  engaged_sessions_90d    30000 non-null  int64
 18  ai_sessions_90d         30000 non-null  int64
 19  scroll_events_90d       30000 non-null  int64
 20  days_with_impressions   30000 non-null  int64
 21  days_with_sessions      30000 non-null  int64
 22  impressions_last_30d    30000 non-null  int64
 23  clicks_last_30d         30000 non-null  int64
 24  sessions_last_30d       30000 non-null  int64
 25  impressions_prev_30d    30000 non-null  int64
 26  clicks_prev_30d         30000 non-null  int64
 27  sessions_prev_30d       30000 non-null  int64
 28  content_age_days        30000 non-null  int64
 29  age_tier                30000 non-null  object
 30  age_tier_order          30000 non-null  int64
 31  days_since_last_update  30000 non-null  int64
 32  freshness_tier          30000 non-null  object
 33  word_count_tier         22301 non-null  object
 34  char_count_tier         22301 non-null  object
 35  ctr                     30000 non-null  float64
 36  avg_position            30000 non-null  float64
 37  engagement_rate         30000 non-null  float64
 38  scroll_rate             29875 non-null  float64
 39  ai_traffic_pct          30000 non-null  float64
 40  impression_tier         30000 non-null  object
 41  position_tier           30000 non-null  object
 42  trend_direction         30000 non-null  object
 43  trend_pct               26612 non-null  float64
dtypes: float64(11), int64(19), object(14)
memory usage: 10.1+ MB

In [11]:
print(df.columns.tolist())

['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

In [12]:
df.head(30)

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,provider_used,model_used,impressions_90d,clicks_90d,pageviews_90d,sessions_90d,users_90d,engaged_sessions_90d,ai_sessions_90d,scroll_events_90d,days_with_impressions,days_with_sessions,impressions_last_30d,clicks_last_30d,sessions_last_30d,impressions_prev_30d,clicks_prev_30d,sessions_prev_30d,content_age_days,age_tier,age_tier_order,days_since_last_update,freshness_tier,word_count_tier,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,NaN,gemini-2.5-flash,3803,29,22,17,16,1,0,1,88,13,578,2,2,987,13,9,187,181-365,5,20,0-30,2000-3500,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,NaN,gemini-3-flash-preview,15320,7,10,9,9,0,0,1,88,9,2501,2,3,5915,1,2,445,365+,6,25,0-30,2000-3500,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,NaN,gemini-2.5-flash,12581,11,14,11,11,0,0,4,88,11,2382,1,1,6089,3,3,141,91-180,4,20,0-30,3500+,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,NaN,NaN,11751,58,87,78,75,1,0,3,88,51,3626,22,35,4206,17,26,463,365+,6,22,0-30,NaN,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,NaN,gemini-3-flash-preview,19140,24,177,145,144,0,0,43,88,33,4211,10,14,6452,2,9,263,181-365,5,14,0-30,2000-3500,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7
5,content_d4084a4bc775,client_f369cb89fc,720.0,1.00,HIGH,1.05,keyword article,transactional,3080.0,18178.0,NaN,gemini-2.5-flash,3970,1,4,5,5,0,0,1,88,5,617,0,4,1009,1,1,147,91-180,4,20,0-30,2000-3500,15000-25000,0.03,8.5,0.00,25.00,0.0,good,page_1,down,-38.9
6,content_9a34b442b552,client_8722616204,0.0,0.00,LOW,0.00,keyword article,informational,3059.0,20810.0,google,gemini-3-flash-preview,20,0,1,1,1,0,0,0,13,1,1,0,0,13,0,1,90,31-90,3,20,0-30,2000-3500,15000-25000,0.00,7.0,0.00,0.00,0.0,low,page_1,down,-92.3
7,content_a63219c6e95a,client_19581e27de,590.0,0.44,MEDIUM,0.64,keyword article,commercial,NaN,NaN,NaN,NaN,1724,1,28,28,28,1,0,2,88,11,636,1,24,632,0,4,445,365+,6,22,0-30,NaN,NaN,0.06,21.2,3.57,7.14,0.0,moderate,page_3_5,stable,0.6
8,content_5e6c160719bc,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,3807.0,24228.0,google,gemini-3-flash-preview,32574,29,128,68,66,4,0,8,83,44,5696,9,36,13828,8,14,90,31-90,3,20,0-30,3500+,15000-25000,0.09,46.0,5.88,6.25,0.0,excellent,page_3_5,down,-58.8
9,content_c27558df2b0c,client_19581e27de,0.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,NaN,NaN,1240,2,4,3,3,0,0,0,88,3,252,0,0,356,0,0,257,181-365,5,104,91-180,NaN,NaN,0.16,4.9,0.00,0.00,0.0,moderate,page_1,down,-29.2
10,content_d8ee6cc6d642,client_19581e27de,20.0,0.03,LOW,2.50,keyword article,commercial,NaN,NaN,NaN,NaN,20919,324,398,326,311,22,0,38,88,74,7665,112,126,6441,117,136,329,181-365,5,104,91-180,NaN,NaN,1.55,2.2,6.75,9.55,0.0,good,top_3,stable,19.0
11,content_5a3e876cf7f7,client_d4735e3a26,NaN,NaN,NaN,NaN,feedly article,NaN,776.0,5527.0,NaN,gpt-4o-mini,1,0,1,1,1,0,0,0,1,1,1,0,0,0,0,0,312,181-365,5,20,0-30,<1000,<8000,0.00,0.0,0.00,0.00,0.0,low,top_3,new,NaN
12,content_42fb2cad9ecf,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,3969.0,24527.0,google,gemini-3-flash-preview,7228,127,459,233,223,8,0,12,88,62,5127,92,159,1357,29,43,124,91-180,4,104,91-180,3500+,15000-25000,1.76,5.6,3.43,2.61,0.0,good,page_1,up,277.8
13,content_a5a2fbc76336,client_8527a891e2,10.0,0.00,LOW,0.00,keyword article,informational,1342.0,8469.0,NaN,gpt-4o-mini,307,0,4,4,4,0,0,1,69,3,85,0,3,77,0,1,238,181-365,5,103,91-180,1000-2000,8000-15000,0.00,39.8,0.00,25.00,0.0,moderate,page_3_5,stable,10.4
14,content_91067a14431a,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,2802.0,18013.0,google,gemini-3-flash-preview,179,0,34,18,18,0,0,1,63,8,20,0,12,57,0,5,124,91-180,4,104,91-180,2000-3500,15000-25000,0.00,27.1,0.00,2.94,0.0,low,page_3_5,down,-64.9
15,content_689414059706,client_9f14025af0,0.0,0.00,LOW,0.00,keyword article,informational,2661.0,17889.0,NaN,gemini-2.5-flash,38,9,15,9,8,3,0,4,17,6,31,7,7,4,0,0,148,91-180,4,8,0-30,2000-3500,15000-25000,23.68,7.8,33.33,26.67,0.0,low,page_1,up,675.0
16,content_78bd1d4a1d4d,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,8200.0,52393.0,NaN,gemini-3-flash-preview,13848,21,528,475,478,1,0,73,88,45,2422,9,31,3975,5,14,307,181-365,5,104,91-180,3500+,25000+,0.15,8.9,0.21,13.83,0.0,good,page_1,down,-39.1
17,content_761a44afda12,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,transactional,NaN,NaN,NaN,NaN,9449,7,118,118,118,14,0,18,88,36,3026,3,80,3792,1,36,421,365+,6,22,0-30,NaN,NaN,0.07,7.3,11.86,15.25,0.0,good,page_1,down,-20.2
18,content_0b360eb9db55,client_349c41201b,30.0,0.01,LOW,0.00,keyword article,transactional,2945.0,19647.0,google,gemini-3-flash-preview,5141,7,44,43,43,1,0,1,88,19,663,3,24,1537,2,13,119,91-180,4,20,0-30,2000-3500,15000-25000,0.14,11.4,2.33,2.27,0.0,good,striking,down,-56.9
19,content_af865035b328,client_f369cb89fc,30.0,1.00,HIGH,1.57,keyword article,transactional,2673.0,16168.0,NaN,gemini-2.5-flash,99,2,2,3,3,0,0,1,56,3,10,0,2,31,0,0,187,181-365,5,20,0-30,2000-3500,15000-25000,2.02,6.9,0.00,50.00,0.0,low,page_1,down,-67.7
20,content_0d748c484ab1,client_f369cb89fc,0.0,0.00,LOW,0.00,keyword article,informational,2692.0,18814.0,google,gemini-3-flash-preview,2538,14,13,13,12,1,0,2,88,12,445,7,7,914,4,4,95,91-180,4,20,0-30,2000-3500,15000-25000,0.55,5.6,7.69,15.38,0.0,moderate,page_1,down,-51.3
21,content_9d548144b06d,client_6208ef0f77,0.0,0.00,LOW,0.00,keyword article,informational,3455.0,21571.0,google,gemini-3-flash-preview,86,0,19,14,14,0,0,0,39,8,20,0,3,18,0,2,118,91-180,4,20,0-30,2000-3500,15000-25000,0.00,12.6,0.00,0.00,0.0,low,striking,stable,11.1
22,content_3fb46bec4413,client_4e07408562,0.0,0.00,LOW,0.00,keyword article,informational,3058.0,20108.0,NaN,gemini-3-flash-preview,2311,3,5,5,4,0,0,1,88,4,292,1,1,469,2,3,228,181-365,5,7,0-30,2000-3500,15000-25000,0.13,3.9,0.00,20.00,0.0,moderate,page_1,down,-37.7
23,content_2da6ae9d0882,client_e629fa6598,0.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,NaN,unknown,297,1,12,12,11,0,0,3,43,8,0,0,3,34,0,3,502,365+,6,20,0-30,NaN,NaN,0.34,13.9,0.00,25.00,0.0,low,striking,down,-100.0
24,content_0e23e310d404,client_19581e27de,0.0,0.00,LOW,0.00,keyword article,informational,NaN,NaN,NaN,NaN,29541,79,129,108,105,1,0,3,88,51,9313,26,46,11748,31,43,257,181-365,5,104,91-180,NaN,NaN,0.27,4.1,0.93,2.33,0.0,good,page_1,down,-20.7
25,content_033ae3e7aecf,client_f369cb89fc,70.0,0.81,HIGH,1.12,keyword article,commercial,2777.0,16215.0,NaN,gemini-2.5-flash,27,0,2,2,2,0,1,0,18,2,9,0,0,14,0,0,180,91-180,4,20,0-30,2000-3500,15000-25000,0.00,7.2,0.00,0.00,50.0,low,page_1,down,-35.7
26,content_72c5c2d73e5a,client_4e07408562,0.0,0.00,LOW,0.00,keyword article,informational,2686.0,17181.0,NaN,gemini-3-flash-preview,2426,3,9,9,9,0,0,1,88,6,743,0,5,818,3,4,300,181-365,5,13,0-30,2000-3500,15000-25000,0.12,30.0,0.00,11.11,0.0,moderate,page_3_5,stable,-9.2
27,content_7ea135180dd9,client_4ec9599fc2,10.0,0.32,LOW,10.57,keyword article,informational,NaN,NaN,NaN,gpt-5-mini,1197,2,6,5,5,0,0,0,81,4,96,0,2,272,0,1,445,365+,6,104,91-180,NaN,NaN,0.17,8.1,0.00,0.00,0.0,moderate,page_1,down,-64.7
28,content_19ad8f9bac29,client_3fdba35f04,480.0,0.58,MEDIUM,1.97,keyword article,informational,1372.0,9052.0,openai,gpt-4o-mini,315,0,12,8,8,0,0,7,46,3,8,0,0,20,0,0,96,91-180,4,20,0-30,1000-2000,8000-15000,0.00,59.3,0.00,58.33,0.0,moderate,deep,down,-60.0
29,content_ba8e51f13800,client_d59eced1de,10.0,0.00,LOW,0.00,keyword article,transactional,1626.0,11107.0,NaN,gpt-4o-mini,19,0,55,28,22,2,0,3,6,19,19,0,13,0,0,15,347,181-365,5,20,0-30,1000-2000,8000-15000,0.00,16.5,7.14,5.45,0.0,low,striking,new,NaN

In [13]:
df.describe(include="all")

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,provider_used,model_used,impressions_90d,clicks_90d,pageviews_90d,sessions_90d,users_90d,engaged_sessions_90d,ai_sessions_90d,scroll_events_90d,days_with_impressions,days_with_sessions,impressions_last_30d,clicks_last_30d,sessions_last_30d,impressions_prev_30d,clicks_prev_30d,sessions_prev_30d,content_age_days,age_tier,age_tier_order,days_since_last_update,freshness_tier,word_count_tier,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
count,30000,30000,27532.000000,27532.000000,27390,27532.000000,30000,27626,22301.000000,22301.000000,8562,24267,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.00000,30000,30000.000000,30000.000000,30000,22301,22301,30000.000000,30000.00000,30000.000000,29875.000000,30000.000000,30000,30000,30000,26612.000000
unique,30000,32,NaN,NaN,3,NaN,3,4,NaN,NaN,2,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,4,4,4,NaN,NaN,NaN,NaN,NaN,4,5,5,NaN
top,content_6880eb215048,client_19581e27de,NaN,NaN,LOW,NaN,keyword article,informational,NaN,NaN,google,gemini-3-flash-preview,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,91-180,NaN,NaN,0-30,2000-3500,15000-25000,NaN,NaN,NaN,NaN,NaN,low,page_1,down,NaN
freq,1,7008,NaN,NaN,22896,NaN,27207,17235,NaN,NaN,7364,13271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11780,NaN,NaN,20480,11263,12055,NaN,NaN,NaN,NaN,NaN,11248,11814,16262,NaN
mean,NaN,NaN,158.882391,0.146954,NaN,0.485342,NaN,NaN,3107.760325,20665.277835,NaN,NaN,5200.366300,16.097333,49.942467,37.066633,35.937700,0.991933,0.204500,4.033500,61.454033,13.096333,1429.058733,4.933867,14.114267,1783.078500,5.435100,10.283000,256.16780,NaN,4.786533,46.098300,NaN,NaN,NaN,0.510733,16.34238,2.534520,18.212921,0.768196,NaN,NaN,NaN,-4.785969
std,NaN,NaN,1518.270825,0.285241,NaN,2.101560,NaN,NaN,1452.382598,10115.344042,NaN,NaN,16838.019547,75.076958,152.101430,107.069131,103.748185,4.359576,1.363601,22.335179,32.689245,17.307759,5643.852081,23.929393,39.036371,6150.429511,28.358673,42.578003,132.70793,NaN,0.790392,42.078709,NaN,NaN,NaN,3.279162,15.21679,8.310096,29.472768,7.429454,NaN,NaN,NaN,473.861780
min,NaN,NaN,0.000000,0.000000,NaN,0.000000,NaN,NaN,8.000000,40.000000,NaN,NaN,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,90.00000,NaN,3.000000,1.000000,NaN,NaN,NaN,0.000000,0.00000,0.000000,0.000000,0.000000,NaN,NaN,NaN,-100.000000
25%,NaN,NaN,0.000000,0.000000,NaN,0.000000,NaN,NaN,2413.000000,15644.000000,NaN,NaN,81.000000,0.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,31.000000,2.000000,10.000000,0.000000,0.000000,19.000000,0.000000,1.000000,132.00000,NaN,4.000000,20.000000,NaN,NaN,NaN,0.000000,6.20000,0.000000,0.000000,0.000000,NaN,NaN,NaN,-62.600000
50%,NaN,NaN,10.000000,0.000000,NaN,0.000000,NaN,NaN,2877.000000,19116.000000,NaN,NaN,731.000000,1.000000,8.000000,7.000000,7.000000,0.000000,0.000000,1.000000,81.000000,6.000000,139.000000,0.000000,3.000000,210.000000,0.000000,2.000000,236.00000,NaN,5.000000,20.000000,NaN,NaN,NaN,0.070000,10.80000,0.000000,5.000000,0.000000,NaN,NaN,NaN,-33.500000
75%,NaN,NaN,20.000000,0.130000,NaN,0.000000,NaN,NaN,3666.000000,24011.000000,NaN,NaN,3615.250000,7.000000,33.000000,27.000000,27.000000,1.000000,0.000000,3.000000,88.000000,16.000000,768.000000,2.000000,12.000000,1143.000000,2.000000,7.000000,333.00000,NaN,5.000000,104.000000,NaN,NaN,NaN,0.290000,22.30000,1.350000,23.530000,0.000000,NaN,NaN,NaN,0.000000
max,NaN,NaN,74000.000000,1.000000,NaN,100.360000,NaN,NaN,9546.000000,111158.000000,NaN,NaN,517715.000000,4178.000000,5998.000000,4345.000000,4913.000000,290.000000,64.000000,2605.000000,88.000000,90.000000,238796.000000,1176.000000,1081.000000,218786.000000,1627.000000,4247.000000,564.00000,NaN,6.000000,373.000000,NaN,NaN,NaN,100.000000,245.00000,100.000000,300.000000,300.000000,NaN,NaN,NaN,44900.000000

In [14]:
df.isnull().sum().sort_values(ascending=False)

provider_used             21438
word_count                 7699
char_count                 7699
word_count_tier            7699
char_count_tier            7699
model_used                 5733
trend_pct                  3388
competition_level          2610
search_volume              2468
cpc                        2468
competition                2468
main_intent                2374
scroll_rate                 125
content_type                  0
client_id                     0
content_id                    0
impressions_90d               0
clicks_90d                    0
pageviews_90d                 0
sessions_90d                  0
days_with_impressions         0
days_with_sessions            0
impressions_last_30d          0
clicks_last_30d               0
users_90d                     0
engaged_sessions_90d          0
ai_sessions_90d               0
scroll_events_90d             0
sessions_prev_30d             0
clicks_prev_30d               0
impressions_prev_30d          0
sessions_last_30d             0
days_since_last_update        0
age_tier_order                0
content_age_days              0
age_tier                      0
ctr                           0
freshness_tier                0
engagement_rate               0
avg_position                  0
ai_traffic_pct                0
impression_tier               0
position_tier                 0
trend_direction               0
dtype: int64

In [16]:
print("Number of Rows:", len(df))
print("Number of Columns:", len(df.columns))

print("\nUnique Clients:", df["client_id"].nunique())
print("Unique Content Pages:", df["content_id"].nunique())

print("\nContent Types:")
print(df["content_type"].value_counts())

print("\nTrend Direction:")
print(df["trend_direction"].value_counts())

Number of Rows: 30000
Number of Columns: 44

Unique Clients: 32
Unique Content Pages: 30000

Content Types:
content_type
keyword article       27207
feedly article         2096
comparison article      697
Name: count, dtype: int64

Trend Direction:
trend_direction
down      16262
stable     5962
up         4388
new        2236
flat       1152
Name: count, dtype: int64

In [17]:
print("Average Search Volume:", round(df["search_volume"].mean(), 2))
print("Average CTR:", round(df["ctr"].mean(), 2))
print("Average Position:", round(df["avg_position"].mean(), 2))

Average Search Volume: 158.88
Average CTR: 0.51
Average Position: 16.34

In [18]:
print("Number of Rows:", len(df))
print("Number of Columns:", len(df.columns))
print("Unique Clients:", df["client_id"].nunique())
print("Unique Content Pages:", df["content_id"].nunique())

Number of Rows: 30000
Number of Columns: 44
Unique Clients: 32
Unique Content Pages: 30000

## 4. Careful words: what I can and can't claim

Although the dataset contains valuable SEO and content performance metrics, it has several limitations. The data represents historical performance and may not capture recent changes in user behavior, search engine algorithms, or seasonal trends. As a result, a page that performed poorly in the past may improve naturally, while a high-performing page may decline due to external factors.

The dataset also does not include qualitative information such as content quality, readability, factual accuracy, or user satisfaction. These factors can significantly influence whether refreshing a page is beneficial.

Therefore, the machine learning model should be used as a **decision-support tool** rather than an automatic decision maker. The model can prioritize pages that appear to have refresh opportunities, but final decisions should be reviewed by SEO specialists or content editors before updates are made.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Self-check

## What I Learned

During this assignment, I learned how to explore a real-world SEO dataset and understand the importance of data exploration before building any machine learning model. I examined the dataset structure, identified the available features, calculated basic statistics, and understood how these features relate to content performance.

I also learned that machine learning is not only about training models but also about clearly defining the business problem, understanding the available data, and recognizing the limitations of the dataset.

## Challenges Faced

The main challenge was understanding the dataset and determining which features were most relevant for identifying content refresh opportunities. I also encountered issues while setting up the notebook and loading the dataset, which helped me become more familiar with the project structure and data loading process.

## Next Steps

In the following weeks, I plan to perform more detailed exploratory data analysis (EDA), engineer meaningful features, build a baseline machine learning model for content refresh scoring, evaluate its performance, and improve it through experimentation and validation.